In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
df=pd.DataFrame()
df=pd.read_csv('gdp.csv', skiprows=4)
df1=df.ix[:,'1990':'2011']
df2 = df1.dropna(thresh=19)
fill_value = pd.DataFrame({col: df2.mean(axis=1) for col in df2.columns})
df2.fillna(fill_value, inplace=True)
df2['avg_gdp'] = df2.mean(axis=1)
df3 = df2.sort('avg_gdp', ascending=True)
df3['country_name'] = df.ix[:,'Country Name']
d1 = df3[df3['country_name'].str.contains('income')]
d2 = df3[df3['country_name'].str.contains('countries')]

d11=d1.ix[:,'1990':'1995']
d11['avg_gdp'] = d11.mean(axis=1)
d11['country_name'] = d1.ix[:,'country_name']

d12=d1.ix[:,'1996':'2000']
d12['avg_gdp'] = d12.mean(axis=1)
d12['country_name'] = d1.ix[:,'country_name']

d13=d1.ix[:,'2001':'2005']
d13['avg_gdp'] = d13.mean(axis=1)
d13['country_name'] = d1.ix[:,'country_name']

d14=d1.ix[:,'2006':'2011']
d14['avg_gdp'] = d14.mean(axis=1)
d14['country_name'] = d1.ix[:,'country_name']

d21=d2.ix[:,'1990':'1995']
d21['avg_gdp'] = d21.mean(axis=1)
d21['country_name'] = d2.ix[:,'country_name']

d22=d2.ix[:,'1996':'2000']
d22['avg_gdp'] = d22.mean(axis=1)
d22['country_name'] = d2.ix[:,'country_name']

d23=d2.ix[:,'2001':'2005']
d23['avg_gdp'] = d23.mean(axis=1)
d23['country_name'] = d2.ix[:,'country_name']

d24=d2.ix[:,'2006':'2011']
d24['avg_gdp'] = d24.mean(axis=1)
d24['country_name'] = d2.ix[:,'country_name']

d11=d11.set_index(['country_name'])
d11.plot(x=d11.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('GDP in USD ')
plt.show()

d14=d14.set_index(['country_name'])
d14.plot(x=d14.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('GDP in USD ')
plt.show()


d21=d21.set_index(['country_name'])
d21.plot(x=d21.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('GDP in USD ')
plt.show()

d24=d24.set_index(['country_name'])
d24.plot(x=d24.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('GDP in USD')
plt.show()

df3=df3.set_index(['country_name'])
#dfd=df3.ix[:, '2011':]
#dfd1=dfd.tail(10)
#dfd1.tail(10)

df4=df3.tail(20)
df4=df4.ix[:,'2005':]
df4.head(10)
df4=df4.drop(['High income', 'High income: OECD'])
#df3=df3.drop(['Low income','Latin America & Caribbean (developing only)','OECD members','European Union','North America','East Asia & Pacific (developing only)','Euro area','High income', 'High income: OECD','Least developed countries: UN classification','High income: nonOECD','Heavily indebted poor countries (HIPC)','Europe & Central Asia (all income levels)','Middle East & North Africa (all income levels)','East Asia & Pacific (all income levels)','Upper middle income','Latin America & Caribbean (all income levels)','Middle income','Low & middle income','Lower middle income','Sub-Saharan Africa (all income levels)','Low income'])
dfg=df3.ix[:,'2006':]
dfg.tail(10)

/Users/haripadbharti/anaconda/lib/python3.4/site-packages/pandas/core/frame.py:2532: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
/Users/haripadbharti/anaconda/lib/python3.4/site-packages/IPython/kernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,2006,2007,2008,2009,2010,2011,avg_gdp
country_name,,,,,,,
Euro area,1.117191e+13,1.286517e+13,1.410447e+13,1.289824e+13,1.263536e+13,1.362165e+13,8.857403e+12
East Asia & Pacific (all income levels),1.070552e+13,1.200140e+13,1.384096e+13,1.424787e+13,1.661608e+13,1.923736e+13,9.338860e+12
United States,1.385589e+13,1.447764e+13,1.471858e+13,1.441874e+13,1.496437e+13,1.551793e+13,1.057816e+13
North America,1.517206e+13,1.594140e+13,1.626731e+13,1.579539e+13,1.658413e+13,1.731227e+13,1.151401e+13
European Union,1.527715e+13,1.766608e+13,1.901278e+13,1.700537e+13,1.693782e+13,1.831000e+13,1.177660e+13
Europe & Central Asia (all income levels),1.797688e+13,2.101691e+13,2.307769e+13,2.031188e+13,2.082207e+13,2.292255e+13,1.373134e+13
High income: OECD,3.748476e+13,4.094412e+13,4.328932e+13,4.072151e+13,4.249859e+13,4.558862e+13,2.977716e+13
OECD members,3.898253e+13,4.263475e+13,4.512093e+13,4.223101e+13,4.428089e+13,4.753456e+13,3.081073e+13
High income,4.083685e+13,4.496369e+13,4.817323e+13,4.484502e+13,4.738561e+13,5.132518e+13,3.230524e+13
World,5.097147e+13,5.745222e+13,6.298283e+13,5.970469e+13,6.548920e+13,7.257225e+13,4.001878e+13

In [20]:
from pandas import ExcelWriter
writer = ExcelWriter('output2.xlsx')
df3.to_excel(writer, 'sheet1')
writer.save()