In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
df=pd.DataFrame()
df=pd.read_csv('forest.csv', skiprows=4)
df1=df.ix[:,'1990':'2011']
df2 = df1.dropna(thresh=19)
fill_value = pd.DataFrame({col: df2.mean(axis=1) for col in df2.columns})
df2.fillna(fill_value, inplace=True)
df2['avg_forestcover'] = df2.mean(axis=1)
df3 = df2.sort('avg_forestcover', ascending=True)
df3['country_name'] = df.ix[:,'Country Name']
d1 = df3[df3['country_name'].str.contains('income')]
d2 = df3[df3['country_name'].str.contains('countries')]

d11=d1.ix[:,'1990':'1995']
d11['avg_forestcover'] = d11.mean(axis=1)
d11['country_name'] = d1.ix[:,'country_name']

d12=d1.ix[:,'1996':'2000']
d12['avg_forestcover'] = d12.mean(axis=1)
d12['country_name'] = d1.ix[:,'country_name']

d13=d1.ix[:,'2001':'2005']
d13['avg_forestcover'] = d13.mean(axis=1)
d13['country_name'] = d1.ix[:,'country_name']

d14=d1.ix[:,'2006':'2011']
d14['avg_forestcover'] = d14.mean(axis=1)
d14['country_name'] = d1.ix[:,'country_name']

d21=d2.ix[:,'1990':'1995']
d21['avg_forestcover'] = d21.mean(axis=1)
d21['country_name'] = d2.ix[:,'country_name']

d22=d2.ix[:,'1996':'2000']
d22['avg_forestcover'] = d22.mean(axis=1)
d22['country_name'] = d2.ix[:,'country_name']

d23=d2.ix[:,'2001':'2005']
d23['avg_forestcover'] = d23.mean(axis=1)
d23['country_name'] = d2.ix[:,'country_name']

d24=d2.ix[:,'2006':'2011']
d24['avg_forestcover'] = d24.mean(axis=1)
d24['country_name'] = d2.ix[:,'country_name']

d11=d11.set_index(['country_name'])
d11.plot(x=d11.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('Forest Cover % ')
plt.show()

d14=d14.set_index(['country_name'])
d14.plot(x=d14.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('Forest Cover % ')
plt.show()


d21=d21.set_index(['country_name'])
d21.plot(x=d21.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('Forest Cover % ')
plt.show()

d24=d24.set_index(['country_name'])
d24.plot(x=d24.index,kind='bar')
#ax.set_xticklabels(d11.index, rotation=180)
plt.xlabel('Country categories ')
plt.ylabel('Forest Cover % ')
plt.show()


df3=df3.set_index(['country_name'])
dff=df3.ix[:,'20011':]
dff1=dff.tail(10)
dff1.head(10)

/Users/haripadbharti/anaconda/lib/python3.4/site-packages/pandas/core/frame.py:2532: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
/Users/haripadbharti/anaconda/lib/python3.4/site-packages/IPython/kernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,avg_forestcover
country_name,,,,,,,,,,,
Guinea-Bissau,74.708393,74.366999,74.025605,73.684211,73.328592,72.972973,72.617354,72.261735,71.906117,71.550498,75.206905
Solomon Islands,80.643087,80.450161,80.257235,80.064309,79.864237,79.664166,79.464094,79.264023,79.063951,78.863880,80.943519
Guyana,84.399289,84.378969,84.358649,84.338329,84.311913,84.285497,84.259081,84.232664,84.206248,84.155448,84.420302
Gabon,85.380525,85.380525,85.380525,85.380525,85.380525,85.380525,85.380525,85.380525,85.380525,86.156712,85.415807
Caribbean small states,85.623441,85.579054,85.534618,85.490206,85.451920,85.413659,85.375398,85.337137,85.298851,85.254613,85.737219
Palau,86.673913,87.000000,87.304348,87.608696,87.608696,87.608696,87.608696,87.608696,87.608696,87.608696,86.055901
Seychelles,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043,88.413043
American Samoa,89.900000,89.750000,89.550000,89.400000,89.250000,89.050000,88.900000,88.750000,88.550000,88.400000,90.165909
"Micronesia, Fed. Sts.",91.300000,91.342857,91.385714,91.414286,91.457143,91.500000,91.528571,91.571429,91.614286,91.657143,91.262585
Suriname,98.608974,98.583333,98.557692,98.532051,98.506410,98.480769,98.455128,98.429487,98.403846,98.379487,98.645892

In [11]:
#Qatar have no forest cover while emits maximum carbon emission.
#Kuwait have forest cover of just 0.27% of the whole land area.

In [26]:
from pandas import ExcelWriter
writer = ExcelWriter('output1.xlsx')
df3.to_excel(writer, 'sheet1')
writer.save()

In [28]:
df3.head(10)

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2003,2004,2005,2006,2007,2008,2009,2010,2011,avg_forestcover
country_name,,,,,,,,,,,,,,,,,,,,,
San Marino,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Qatar,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Greenland,0.000644,0.000644,0.000644,0.000644,0.000644,0.000644,0.000644,0.000536,0.000536,0.000536,...,0.000536,0.000536,0.000536,0.000536,0.000536,0.000536,0.000536,0.000536,0.000536,0.000570
Oman,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,...,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462,0.006462
Faeroe Islands,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,...,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307,0.057307
"Egypt, Arab Rep.",0.044201,0.045708,0.047215,0.048722,0.050229,0.051735,0.053242,0.054749,0.056256,0.057763,...,0.064092,0.065699,0.067306,0.067909,0.068512,0.069114,0.069717,0.070320,0.070923,0.059366
Libya,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,...,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328,0.123328
Djibouti,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,...,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588,0.241588
Kuwait,0.193603,0.201459,0.209315,0.217172,0.225028,0.232884,0.240741,0.248597,0.256453,0.264310,...,0.295735,0.303591,0.311448,0.319304,0.327160,0.335017,0.342873,0.350730,0.350730,0.275737
Iceland,0.160599,0.173267,0.185935,0.198603,0.211272,0.223940,0.236608,0.249277,0.261945,0.274613,...,0.333367,0.348728,0.364090,0.376459,0.388828,0.401197,0.413566,0.425935,0.438903,0.298866